version: "3.5"

services:
  php_fpm:
      build: .
      container_name: inci_php_fpm
      working_dir: /usr/share/nginx/inci
      networks:
        - inci
      volumes:
          - ./:/usr/share/nginx/inci

  nginx:
      image: nginx:1.15
      container_name: inci_nginx
      working_dir: /usr/share/nginx/inci
      networks:
        - inci
      ports:
          - "8080:80"
      volumes:
          - ./:/usr/share/nginx/inci
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
      image: mysql:5.7
      container_name: inci_mysql
      networks:
        - inci
      environment:
        - MYSQL_DATABASE=sistemas
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_USER=inci
        - MYSQL_PASSWORD=password
  # phpMyAdmin container
  phpmyadmin:
    # Use phpmyadmin/phpmyadmin:5.0.2 image
    image: phpmyadmin/phpmyadmin:5.0.2
    # Connect to "my-network" network, as defined below
    networks:
      - inci
    # Map port 8080 on the host to port 80 inside the container
    # Syntax is: "HOST_PORT:CONTAINER_PORT"
    ports:
      - "8081:80"
    # Pass a list of environment variables to the container
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 64M
    # Wait for "mysql" container to start first
    depends_on:
      - mysql

networks:
  inci:
    driver: bridge
